// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZaoFQxezlUgObxIoNpPGO0ABuNSEquno',
    appId: '1:677726543150:web:da684d8bff4c804b002ebf',
    messagingSenderId: '677726543150',
    projectId: 'lapwiseandroid',
    authDomain: 'lapwiseandroid.firebaseapp.com',
    storageBucket: 'lapwiseandroid.firebasestorage.app',
    measurementId: 'G-7NWC75CLC8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgTR8Z2xDXuYKOsLF5XZLJmxzu6IWBeJA',
    appId: '1:677726543150:android:6090c9613f313159002ebf',
    messagingSenderId: '677726543150',
    projectId: 'lapwiseandroid',
    storageBucket: 'lapwiseandroid.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCs8mUt4u2fY6e-_bo7AHSiuBiFPFSjjVE',
    appId: '1:677726543150:ios:0114f8da19538cbd002ebf',
    messagingSenderId: '677726543150',
    projectId: 'lapwiseandroid',
    storageBucket: 'lapwiseandroid.firebasestorage.app',
    iosBundleId: 'com.example.lapwiseCatalogueApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCs8mUt4u2fY6e-_bo7AHSiuBiFPFSjjVE',
    appId: '1:677726543150:ios:0114f8da19538cbd002ebf',
    messagingSenderId: '677726543150',
    projectId: 'lapwiseandroid',
    storageBucket: 'lapwiseandroid.firebasestorage.app',
    iosBundleId: 'com.example.lapwiseCatalogueApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZaoFQxezlUgObxIoNpPGO0ABuNSEquno',
    appId: '1:677726543150:web:38fc48784d9c75e6002ebf',
    messagingSenderId: '677726543150',
    projectId: 'lapwiseandroid',
    authDomain: 'lapwiseandroid.firebaseapp.com',
    storageBucket: 'lapwiseandroid.firebasestorage.app',
    measurementId: 'G-3SJNDGKBJC',
  );
}
